import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'app_mode.dart';

class LanguageProvider extends ChangeNotifier {
  static const _key = 'vision7-lang';
  final SharedPreferences _prefs;

  AppLanguage _lang = AppLanguage.en;
  bool _isReady = false;

  LanguageProvider(this._prefs) {
    _loadLanguage();
  }

  static LanguageProvider of(BuildContext context) {
    return Provider.of<LanguageProvider>(context, listen: false);
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // Common
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.cancel': 'Cancel',
      'common.back': 'Back',
      'common.noResults': 'No results found',
      'common.bookNow': 'Book Now',
      'common.exploreMembership': 'Explore Membership',
      'common.enquireNow': 'Enquire Now',
      'common.save': 'Save',
      'common.delete': 'Delete',
      'common.confirm': 'Confirm',
      'common.success': 'Success',
      'common.retry': 'Retry',
      'common.ok': 'OK',
      'common.share': 'Share',
      'common.viewBookings': 'View My Bookings',
      'common.idToken': 'ID Token',

      // Auth
      'auth.loginTitle': 'Welcome Back',
      'auth.loginSubtitle': 'Sign in to your Vision7 account',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.signIn': 'Sign In',
      'auth.signInWithBiometrics': 'Sign in with Biometrics',
      'auth.forgotPassword': 'Forgot password?',
      'auth.resetPassword': 'Reset Password',
      'auth.noAccount': "Don't have an account?",
      'auth.hasAccount': 'Already have an account?',
      'auth.signUp': 'Sign Up',
      'auth.agreeToPrefix': 'I agree to the ',
      'auth.agreeToMiddle': ' and ',
      'auth.mustAgreeToTerms': 'Please accept the Terms of Service and Privacy Policy to continue',
      'auth.validation.emailRequired': 'Email is required',
      'auth.validation.emailInvalid': 'Invalid email address',
      'auth.validation.passwordRequired': 'Password is required',
      'auth.validation.passwordMinLength': 'Password must be at least 8 characters',
      'auth.validation.nameRequired': 'Name is required',
      'auth.logout': 'Logout',
      'auth.logoutConfirm': 'Are you sure you want to logout?',
      'auth.deleteAccount': 'Delete Account',
      'auth.deleteAccountConfirm':
          'This permanently deletes your account and personal data. This cannot be undone. Are you sure?',
      'auth.deleteAccountFailed': 'Could not delete your account. Please try again.',
      'auth.googleFailed': 'Google sign-in failed. Please try again.',
      'auth.appleFailed': 'Apple sign-in failed. Please try again.',
      'auth.google': 'Google',
      'auth.apple': 'Apple',
      'auth.orContinueWith': 'Or continue with',
      'auth.orSignInWith': 'Or sign in with',
      'auth.googleSignIn': 'Google Sign-In',
      'auth.appleSignIn': 'Apple Sign-In',
      'auth.emailHint': 'your@email.com',
      'auth.passwordHint': 'Enter password',
      'auth.confirmPasswordHint': 'Enter password',

      // Register
      'register.title': 'Create Account',
      'register.subtitle': 'Join Vision7 today',
      'register.name': 'Full Name',
      'register.email': 'Email Address',
      'register.password': 'Password',
      'register.confirmPassword': 'Confirm Password',
      'register.phone': 'Phone Number (optional)',
      'register.gender': 'Gender (optional)',
      'register.createAccount': 'Create Account',
      'register.nameHint': 'Enter your full name',
      'register.emailHint': 'your@email.com',
      'register.passwordHint': 'Enter password',

      // Forgot Password
      'forgot.title': 'Reset Password',
      'forgot.subtitle': 'Enter your email to receive reset instructions',
      'forgot.sendLink': 'Send Reset Link',
      'forgot.sent': 'Check your email for reset instructions',
      'forgot.emailHint': 'your@email.com',
      'forgot.backToLogin': 'Back to login',

      // Onboarding
      'onboarding.welcome': 'Welcome to Vision7',
      'onboarding.title': 'VISION7',
      'onboarding.subtitle': 'Your premium wellness and sports destination',
      'onboarding.next': 'Next',
      'onboarding.getStarted': 'Get Started',
      'onboarding.skip': 'Skip',

      // Home
      'home.title': 'Welcome to Vision7\nLeisure',
      'home.subtitle': 'Your premium wellness and sports experience',
      'home.greeting.morning': 'Good Morning',
      'home.greeting.afternoon': 'Good Afternoon',
      'home.greeting.evening': 'Good Evening',
      'home.experiencesTitle': 'Experiences',
      'home.focusAreasTitle': 'What Sets Us Apart',
      'home.bookATour': 'Book a Tour',
      'home.exploreMore': 'Explore More',
      'home.viewAll': 'View All',
      'home.experience.padel': 'Padel',
      'home.experience.football5': '5-A-SIDE',
      'home.experience.football7': '7-A-SIDE',
      'home.experience.football9': '9-A-SIDE',
      'home.experience.football11': '11-A-SIDE',
      'home.experience.v7arena': 'V7 Arena',
      'home.experience.birthday': 'Birthday',
      'home.experience.padel.subtitle': 'World-class courts',
      'home.experience.football.subtitle': 'Book a pitch',
      'home.experience.football11.subtitle': 'Full field',
      'home.experience.football9.subtitle': '3VS3 Smart Pitch',
      'home.experience.birthday.subtitle': 'Packages available',
      'home.experience.gym': 'Gym',
      'home.experience.gym.subtitle': 'Fully equipped',
      'home.experience.swimming': 'Swimming',
      'home.experience.swimming.subtitle': 'Lap pool',
      'home.experience.wellness': 'Wellness',
      'home.experience.wellness.subtitle': 'Spa & recovery',
      'home.experience.rooftop': 'Rooftop',
      'home.experience.rooftop.subtitle': 'Lounge & views',
      'home.experience.community': 'Community',
      'home.experience.community.subtitle': 'Events & socials',
      'home.experience.comingSoon': 'Coming Soon',
      'home.focusArea.premium': 'Premium Quality',
      'home.focusArea.coaches': 'Expert Coaches',
      'home.focusArea.booking': 'Easy Booking',

      // Academy
      'academy.home.title': 'Welcome to Vision7\nFootball',
      'academy.pillar.passion': 'Passion',
      'academy.pillar.excellence': 'Excellence',
      'academy.pillar.integrity': 'Integrity',
      'academy.pillar.community': 'Community',
      'academy.pillar.coaching': 'Football',
      'academy.pillar.coaching.subtitle': 'UEFA & AFC Certified Coaching.',
      'academy.pillar.development': 'Development',
      'academy.pillar.development.subtitle': 'Education, welfare, lifestyle',
      'academy.pillar.competition': 'Performance',
      'academy.pillar.competition.subtitle': 'Sports Science & Athletic Performance',
      'academy.about.title': 'FOOTBALL\nMEMBERSHIP',
      'academy.programs': 'Programs',
      'academy.facilities': 'Facilities',
      'academy.coaches': 'Coaches',
      'academy.events': 'Events',
      'academy.contact': 'Contact',
      'academy.register': 'Register',
      'academy.registerCta': 'Register Your Interest',
      'academy.register.hint.fullName': 'Full name',
      'academy.register.hint.parentName': 'Full name',
      'academy.register.hint.age': 'Age',
      'academy.register.hint.program': 'Select program',
      'academy.quickLink.programs': 'Programs',
      'academy.quickLink.facilities': 'Facilities',
      'academy.quickLink.coaches': 'Coaches',
      'academy.quickLink.events': 'Events',
      'academy.quickLink.contact': 'Contact',
      'academy.quickLink.register': 'Register',

      // Explore
      'explore.title': 'Explore',
      'explore.search': 'Search facilities...',
      'explore.all': 'All',
      'explore.noResults': 'No facilities found',
      'explore.filterBy': 'Filter by category',
      'explore.category.padel': 'Indoor Performance Hub',
      'explore.category.padel.leisure': 'Padel',
      'explore.category.gym': 'Gym',
      'explore.category.wellness': 'Wellness',
      'explore.category.rooftop': 'Rooftop',
      'explore.category.swimming': 'Swimming',
      'explore.swimming.beginner': 'Beginner Program',
      'explore.swimming.beginner.sub': 'Learn water safety and basic swimming skills.',
      'explore.swimming.technique': 'Technique Development',
      'explore.swimming.technique.sub': 'Improve stroke technique and breathing control.',
      'explore.swimming.junior': 'Junior Swim',
      'explore.swimming.junior.sub': 'Structured swim development for young swimmers.',
      'explore.swimming.performance': 'Performance Squad',
      'explore.swimming.performance.sub': 'Advanced training for competitive swimmers.',
      'explore.swimming.coaching': 'Private Coaching',
      'explore.swimming.coaching.sub': 'One-on-one sessions with certified swim coaches.',
      'explore.swimming.adult': 'Adult Swim Training',
      'explore.swimming.adult.sub': 'Build confidence and improve endurance.',
      'explore.wellness.heading': 'THE WELLNESS JOURNEY',
      'explore.wellness.subtitle': 'Experience a holistic wellness journey tailor-made for relaxation and revitalisation.',
      'explore.wellness.hydrotherapy': 'Hydrotherapy',
      'explore.wellness.hydrotherapy.sub': 'Revitalising hydro pools',
      'explore.wellness.spa': 'Spa',
      'explore.wellness.spa.sub': 'Luxury curated spa',
      'explore.wellness.sauna': 'Sauna',
      'explore.wellness.sauna.sub': 'State-of-the-art sauna',
      'explore.wellness.coldPlunge': 'Cold Plunge',
      'explore.wellness.coldPlunge.sub': 'Invigorating cold plunge',
      'explore.wellness.treatments': 'Treatments',
      'explore.wellness.treatments.sub': 'Personalised healing',
      'explore.wellness.therapists': 'Therapists',
      'explore.wellness.therapists.sub': 'Experienced therapists',
      'explore.comingSoon': 'Coming Soon',
      'explore.padelCourt.name': 'Padel Court',
      'explore.padelCourt.sessionLength': 'Session Length',
      'explore.padelCourt.mins': 'mins',
      'explore.padelCourt.bookACourt': 'Book a Court',
      'explore.padelCourt.facilitiesHeading': 'Padel Facilities',
      'explore.padelCourt.facility.courts': 'Premium Courts',
      'explore.padelCourt.facility.courts.sub': 'High quality courts',
      'explore.padelCourt.facility.towels': 'Towel Service',
      'explore.padelCourt.facility.towels.sub': 'Complimentary towels',
      'explore.padelCourt.facility.refreshments': 'Refreshments',
      'explore.padelCourt.facility.refreshments.sub': 'Drinks & light snacks',
      'explore.padelCourt.facility.lounge': 'Player Lounge',
      'explore.padelCourt.facility.lounge.sub': 'Lounge & social area',
      'explore.padelCourt.facility.coaching': 'Private Coaching',
      'explore.padelCourt.facility.coaching.sub': 'Guidance from experts',
      'explore.padelCourt.facility.memberships': 'Padel Memberships',
      'explore.padelCourt.facility.memberships.sub': 'Exclusive member benefits',
      'explore.gym.poweredBy': 'POWERED BY',
      'explore.gym.heading': 'THE TRAINING ENVIRONMENT',
      'explore.gym.subtitle': 'Train harder. Recover better.',
      'explore.gym.feature1': 'State-of-the-art Technogym equipment',
      'explore.gym.feature2': 'AI powered training programs',
      'explore.gym.feature3': 'Personal training',
      'explore.gym.amenity.gymAccess': 'Gym Access',
      'explore.gym.amenity.steam': 'Steam',
      'explore.gym.amenity.sauna': 'Sauna',
      'explore.gym.amenity.jacuzzi': 'Jacuzzi',
      'explore.gym.amenity.pool': 'Pool',
      'explore.gym.membershipsHeading': 'Gym Memberships',
      'explore.gym.plan.oneMonth': '1 Month',
      'explore.gym.plan.threeMonths': '3 Months',
      'explore.gym.plan.sixMonths': '6 Months',
      'explore.gym.plan.annual': 'Annual Health & Leisure Package',
      'explore.gym.plan.dailyPass': 'Daily Pass',
      'explore.package.oneMonthAdult': '1 Month Adult',
      'explore.package.oneMonthJunior': '1 Month Junior',
      'explore.package.threeMonthAdult': '3-Month Adult',
      'explore.package.threeMonthJunior': '3-Month Junior',
      'explore.package.benefit1': '1 hour daily access to all zones',
      'explore.package.benefit2': 'Smart Pitch shared access (subj. to availability)',
      'explore.category.football': 'Facilities Bookings',
      'explore.football.feature1': 'FIFA-Approved Turf',
      'explore.football.feature2': 'World-Class European Equipment',
      'explore.football.feature3': 'Stadium Lighting',
      'explore.football.feature4': 'Changing Rooms & Showers',
      'explore.football.feature5': 'Rooftop Lounge Access',
      'explore.football.feature6': 'Complimentary Bottled Water',
      'explore.football.package5': '5-A-Side',
      'explore.football.package7': '7-A-Side',
      'explore.football.package9': '9-A-Side',
      'explore.football.package11': '11-A-Side',
      'explore.football.duration60': '60 mins',
      'explore.football.duration90': '90 mins',
      'explore.football.duration2h': '2 hours',
      'explore.category.v7arena': 'V7 Arena',
      'explore.arena.feature1': 'VR & Gaming Zone',
      'explore.arena.feature2': 'Power Shot Testing',
      'explore.arena.feature3': 'Accuracy Circles',
      'explore.arena.feature4': 'Performance Data Tech',
      'explore.arena.feature5': 'Tactical Analysis Room',
      'explore.arena.membersGame': '3vs3 Game: Members',
      'explore.arena.nonMembersGame': '3vs3 Game: Non-Members',
      'explore.arena.gameDuration': '45 minutes with coach & lights',
      'explore.category.birthday': 'Birthday',
      'explore.birthday.packageName': 'Birthday Packages',
      'explore.birthday.packageDesc': '2 hour party: full private use, refreshments, food & birthday certificate',
      'explore.category.other': 'Other',

      // Booking
      'booking.title': 'Book Facility',
      'booking.confirm': 'Confirm Booking',
      'booking.yourDetails': 'Your Details',
      'booking.name': 'Full Name',
      'booking.email': 'Email',
      'booking.phone': 'Phone Number',
      'booking.date': 'Date',
      'booking.time': 'Time',
      'booking.facility': 'Facility',
      'booking.price': 'Price',
      'booking.guests': 'Guests',
      'booking.status': 'Status',
      'booking.confirmed': 'Confirmed',
      'booking.pending': 'Pending',
      'booking.cancelled': 'Cancelled',
      'booking.confirmationTitle': 'Booking Confirmed!',
      'booking.confirmationMsg': 'Your booking has been confirmed',
      'booking.share': 'Share',
      'booking.close': 'Close',
      'booking.qrCode': 'Show QR Code',
      'booking.id': 'Booking ID',
      'booking.total': 'Total',
      'booking.detail.title': 'Booking Details',
      'booking.facilityNotFound': 'Facility not found',
      'booking.notFound': 'Booking not found',
      'booking.priceFormat': 'SAR {price} / {duration}min',
      'booking.pricePerSlot': 'SAR {price}',
      'booking.slotDuration': '{duration} min slots',

      // Bookings
      'bookings.title': 'My Bookings',
      'bookings.upcoming': 'Upcoming',
      'bookings.past': 'Past',
      'bookings.noBookings': 'No bookings yet',
      'bookings.noBookingsSubtitle': 'Explore facilities and make your first booking',
      'bookings.cancelled': 'Cancelled',
      'bookings.noUpcoming': 'No upcoming bookings',
      'bookings.noPast': 'No past bookings',
      'bookings.idLabelEn': 'Booking ID',
      'bookings.idLabelAr': 'رقم الحجز',

      // Booking
      'booking.defaultFacility': 'Facility Booking',
      'booking.detail.failedToLoad': 'Failed to load booking',

      // Facility
      'facility.amenities': 'Amenities',
      'facility.hours': 'Hours',
      'facility.notFound': 'Facility not found',

      // Calendar
      'calendar.day.1': 'Mon',
      'calendar.day.2': 'Tue',
      'calendar.day.3': 'Wed',
      'calendar.day.4': 'Thu',
      'calendar.day.5': 'Fri',
      'calendar.day.6': 'Sat',
      'calendar.day.7': 'Sun',
      'calendar.month.1': 'January',
      'calendar.month.2': 'February',
      'calendar.month.3': 'March',
      'calendar.month.4': 'April',
      'calendar.month.5': 'May',
      'calendar.month.6': 'June',
      'calendar.month.7': 'July',
      'calendar.month.8': 'August',
      'calendar.month.9': 'September',
      'calendar.month.10': 'October',
      'calendar.month.11': 'November',
      'calendar.month.12': 'December',

      // Tab Bar
      'tab.home': 'Home',
      'tab.explore': 'Explore',
      'tab.bookings': 'Bookings',
      'tab.membership': 'Membership',
      'tab.profile': 'Profile',

      // Home
      'home.tourSubtitle': 'See our facilities in person',

      // Membership
      'membership.title': 'Membership',
      'membership.active': 'Active Plan',
      'membership.invoices': 'Invoices',
      'membership.plans': 'Available Plans',
      'membership.enquire': 'Enquire',
      'membership.subscribe': 'Subscribe',
      'membership.invoiceDetail': 'Invoice Details',
      'membership.invoiceItems': 'Items',
      'membership.invoiceTotal': 'Total',
      'membership.invoiceDate': 'Date',
      'membership.invoiceStatus': 'Status',
      'membership.invoicePaid': 'Paid',
      'membership.invoicePending': 'Pending',
      'membership.noInvoices': 'No invoices yet',
      'membership.activePlan': 'Active Plan',
      'membership.noActive': 'No active membership',
      'membership.validUntil': 'Valid until',
      'membership.upgrade': 'Upgrade',
      'membership.availablePlans': 'Available Plans',
      'membership.history': 'History',
      'membership.noPlans': 'No plans available',
      'membership.plan.gold': 'Gold Membership',
      'membership.period.month': 'mo',
      'membership.period.day': 'day',

      // Profile
      'profile.title': 'Profile',
      'profile.account': 'Account',
      'profile.preferences': 'Preferences',
      'profile.about': 'About',
      'profile.bookings': 'My Bookings',
      'profile.membership': 'Membership',
      'profile.invoices': 'Invoices',
      'profile.accessPass': 'Access Pass',
      'profile.notifications': 'Notifications',
      'profile.language': 'Language',
      'profile.languageCurrent': 'English',
      'profile.languageOptionEn': 'English',
      'accessPass.title': 'Access Pass',
      'accessPass.showAtDoor': 'Show this code to any Vision7 door reader',
      'accessPass.validUntil': 'Valid until',
      'accessPass.expired': 'Expired',
      'accessPass.noPass': 'No active pass',
      'accessPass.noPassBody':
          'A QR access pass will appear here once staff issue one for your membership or booking.',
      'common.somethingWentWrong': 'Something went wrong',
      'profile.languageOptionAr': 'العربية',
      'profile.mode': 'Mode',
      'profile.leisureMode': 'Leisure',
      'profile.academyMode': 'Academy',
      'profile.privacyPolicy': 'Privacy Policy',
      'profile.termsOfService': 'Terms of Service',
      'profile.aboutApp': 'About Vision7',
      'profile.version': 'Version',
      'profile.guestUser': 'Guest User',
      'profile.memberSince': 'Member since',
      'profile.failedToLoad': 'Failed to load profile',
      'profile.editProfile': 'Edit Profile',

      // Enquiry
      'enquiry.title': 'Enquiry',
      'enquiry.subtitle': 'Tell us about your requirements',
      'enquiry.membershipType': 'Membership Type',
      'enquiry.fitnessGoal': 'Fitness Goal',
      'enquiry.experience': 'Experience Level',
      'enquiry.preferredTime': 'Preferred Time',
      'enquiry.howHeard': 'How did you hear about us?',
      'enquiry.message': 'Message',
      'enquiry.hint.name': 'Enter your name',
      'enquiry.hint.message': 'Tell us more...',
      'enquiry.submit': 'Submit Enquiry',
      'enquiry.success': 'Enquiry submitted successfully!',

      // Tour Booking
      'tourBooking.title': 'Book a Tour',
      'tourBooking.subtitle': 'Schedule your visit to Vision7',
      'tourBooking.selectDate': 'Select Date',
      'tourBooking.selectTime': 'Select Time',
      'tourBooking.yourInfo': 'Your Information',
      'tourBooking.interests': 'Areas of Interest',
      'tourBooking.confirm': 'Confirm Booking',
      'tourBooking.success': 'Tour booked successfully!',
      'tour.hint.name': 'Enter your full name',

      // Notifications
      'notifications.title': 'Notifications',
      'notifications.noNotifications': 'No notifications yet',
      'notifications.markAllRead': 'Mark all as read',
      'notifications.justNow': 'Just now',

      // Facility Detail
      'facilityDetail.amenities': 'Amenities',
      'facilityDetail.hours': 'Opening Hours',
      'facilityDetail.description': 'Description',
      'facilityDetail.bookNow': 'Book Now',
      'facilityDetail.availableSlots': 'Available Slots',
      'facilityDetail.noSlots': 'No slots available',
      'facilityDetail.genderRule': 'Gender Rule',
      'facilityDetail.mixed': 'Mixed',
      'facilityDetail.maleOnly': 'Male Only',
      'facilityDetail.femaleOnly': 'Female Only',
      'facilityDetail.pricePerSlot': 'Per Slot',
      'facilityDetail.duration': 'Duration',
      // --- Auto-added: missing keys sweep ---
      'academy.about.subtitle': 'Premier football academy in Riyadh',
      'academy.about.missionTitle': 'Our Mission',
      'academy.about.mission': 'To nurture the next generation of football champions by combining technical excellence with character development.',
      'academy.about.intro': 'Vision7 Academy is dedicated to developing young football talent through world-class coaching, state-of-the-art facilities, and a structured development pathway.',
      'academy.about.stats': 'By the Numbers',
      'academy.about.players': 'Players',
      'academy.about.coaches': 'Coaches',
      'academy.about.trophies': 'Trophies',
      'academy.coaches.title': 'Our Coaches',
      'academy.coaches.subtitle': 'Certified, experienced coaching staff',
      'academy.coaches.role': 'Role',
      'academy.coaches.experience': 'Experience',
      'academy.contact.title': 'Contact Us',
      'academy.contact.subtitle': 'Get in touch with our academy team',
      'academy.contact.call': 'Call Us',
      'academy.contact.email': 'Send Email',
      'academy.contact.hours': 'Sun-Thu: 8AM - 10PM',
      'academy.events.title': 'Events',
      'academy.events.subtitle': 'Tournaments, camps, and showcases',
      'academy.facilities.title': 'Academy Facilities',
      'academy.facilities.subtitle': 'World-class training facilities',
      'academy.home.aboutText': '2026/27',
      'academy.home.quickLinks': 'Quick Links',
      'academy.programs.title': 'Programs',
      'academy.programs.subtitle': 'Choose the right program for your level',
      'academy.register.title': 'Register for Academy',
      'academy.register.subtitle': 'Start your academy journey',
      'academy.register.playerName': 'Player Name',
      'academy.register.parentName': 'Parent/Guardian Name',
      'academy.register.age': 'Player Age',
      'academy.register.phone': 'Phone Number',
      'academy.register.program': 'Program',
      'academy.register.submit': 'Submit Registration',
      'academy.register.success': 'Registration submitted successfully!',
      'academy.title': 'Academy Mode',
      'auth.backToLogin': 'Back to Login',
      'auth.confirmPassword': 'Confirm Password',
      'auth.createAccount': 'Create Account',
      'auth.forgotPasswordSubtitle': 'Enter your email and we\'ll send you a reset link',
      'auth.forgotPasswordTitle': 'Forgot Password?',
      'auth.fullName': 'Full Name',
      'auth.haveAccount': 'Already have an account? ',
      'auth.nameHint': 'Enter your full name',
      'auth.registerSubtitle': 'Join Vision7 today',
      'auth.resetLinkSent': 'Reset link sent!',
      'auth.resetLinkSentSubtitle': 'Check your email for reset instructions',
      'auth.sendResetLink': 'Send Reset Link',
      'auth.validation.confirmPasswordRequired': 'Please confirm your password',
      'auth.validation.fullNameRequired': 'Please enter your full name',
      'auth.validation.passwordMismatch': 'Passwords do not match',
      'booking.cancel.confirm': 'Are you sure you want to cancel this booking for {date}?',
      'booking.cancel.label': 'Cancel Booking',
      'booking.cancel.title': 'Cancel Booking',
      'booking.confirmation.facility': 'Facility',
      'booking.confirmation.message': 'Your booking has been confirmed.',
      'booking.continue': 'Continue',
      'booking.defaultFacilityTitle': 'Facility Booking',
      'booking.error': 'Booking failed. Please try again.',
      'booking.notes': 'Special requests...',
      'common.done': 'Done',
      'common.no': 'No',
      'common.select': 'Select an option',
      'common.yes': 'Yes',
      'enquiry.city': 'City / Area',
      'enquiry.currentLevel': 'Current Level',
      'enquiry.email': 'Email',
      'enquiry.enquiringFor': 'Enquiring For',
      'enquiry.error': 'Failed to submit enquiry. Please try again.',
      'enquiry.fullName': 'Full Name',
      'enquiry.gender': 'Gender',
      'enquiry.goal': 'Goal',
      'enquiry.hint.age': 'Age',
      'enquiry.hint.city': 'e.g. Riyadh',
      'enquiry.hint.fullName': 'Your full name',
      'enquiry.hint.medicalNotes': 'Any injuries, conditions or allergies we should know about',
      'enquiry.hint.playerName': 'Player\'s full name',
      'enquiry.hint.preferredDays': 'e.g. Weekday evenings, weekend mornings',
      'enquiry.howDidYouHear': 'How Did You Hear About Us?',
      'enquiry.language': 'Preferred Language',
      'enquiry.medicalNotes': 'Medical Notes (optional)',
      'enquiry.phone': 'Phone *',
      'enquiry.playerAge': 'Player Age',
      'enquiry.playerName': 'Player Name',
      'enquiry.preferredDays': 'Preferred Days / Times',
      'enquiry.preferredProgram': 'Preferred Program',
      'enquiry.regarding': 'Enquiring about',
      'enquiry.submitted': 'Enquiry submitted successfully!',
      'invoices.detail': 'Invoice Details',
      'invoices.lineItems': 'Line Items',
      'invoices.none': 'No invoices yet',
      'invoices.number': 'Invoice',
      'invoices.payment': 'Payment',
      'invoices.title': 'Invoices',
      'membership.endDate': 'End Date',
      'membership.familyMembers': 'Family Members',
      'membership.loadFailed': 'Failed to load membership data',
      'membership.renewsIn': 'Renews in {n} days',
      'membership.renewsToday': 'Renews today',
      'membership.startDate': 'Start Date',
      'membership.status.active': 'Active',
      'membership.status.cancelled': 'Cancelled',
      'membership.status.expired': 'Expired',
      'membership.status.frozen': 'Frozen',
      'membership.status.pending': 'Pending',
      'payment.confirm': 'Confirm & Pay',
      'payment.confirmMessage': 'Purchase {plan} for {price}?',
      'payment.confirmTitle': 'Confirm Purchase',
      'payment.failed': 'Payment failed. Please try again.',
      'payment.method': 'Payment Method',
      'payment.selectMethod': 'Select how you want to pay',
      'payment.success': 'Payment successful! Membership activated.',
      'profile.myBookings': 'My Bookings',
      'profile.updated': 'Profile updated',
      'settings.language': 'Language',
      'settings.mode': 'Mode',
      'settings.title': 'Settings',
      'tour.availableTimes': 'AVAILABLE TIMES',
      'tour.confirm': 'CONFIRM TOUR BOOKING',
      'tour.confirmed': 'Tour booked for {date} at {time}',
      'tour.email': 'Email',
      'tour.error': 'Failed to book tour. Please try again.',
      'tour.eyebrow.academy': 'VISION7 ACADEMY',
      'tour.eyebrow.leisure': 'VISION7 LEISURE',
      'tour.female': 'Female',
      'tour.female.hours': '6am – 3pm',
      'tour.left': 'left',
      'tour.male': 'Male',
      'tour.male.hours': '4pm – 1am',
      'tour.name': 'Full Name',
      'tour.noSlots': 'No time slots available for this window',
      'tour.phone': 'Phone Number',
      'tour.phoneHint': 'A phone number lets us confirm your visit.',
      'tour.pickTimeToContinue': 'PICK A TIME TO CONTINUE',
      'tour.step1': '1 · PICK A DATE',
      'tour.subtitle': 'See the gym, pool, padel courts and wellness spaces for yourself. Choose a day and time and our team will give you a personal walk-through.',
      'tour.title': 'Tour our Leisure Club',
      'tour.title.academy': 'Tour our Academy',
      'validation.ageRange': 'Age must be 5-25',
      'validation.emailInvalid': 'Invalid email',
      'validation.required': 'Required',
      'membership.academyPlan.fullSeason.tag': 'BEST VALUE',
      'membership.academyPlan.fullSeason.title': 'FULL SEASON',
      'membership.academyPlan.fullSeason.benefit1': 'World Leading Practitioners',
      'membership.academyPlan.fullSeason.benefit2': 'UEFA Qualified Coaches, With Top Premier League Club Experience',
      'membership.academyPlan.fullSeason.benefit3': 'State Of The Art European Equipment, Sourced By 1 Of Only 5 FIFA Approved Distributors Across The World',
      'membership.academyPlan.fullSeason.benefit4': 'FIFA Size Pitches',
      'membership.academyPlan.fullSeason.benefit5': 'State Of The Art Stadium Style Lighting',
      'membership.academyPlan.fullSeason.benefit6': 'All Staff Fully Vetted And Screened Ensuring DBS, Safeguarding, And First Aid Certified',
      'membership.academyPlan.fullSeason.benefit7': 'Head Of Medical + Fully Qualified Physiotherapy Team',
      'membership.academyPlan.fullSeason.benefit8': 'Fully Equipped Medical Room With All Emergency Medical Equipment On Site',
      'membership.academyPlan.fullSeason.benefit9': 'Emergency Action Plan Throughout Site',
      'membership.academyPlan.fullSeason.benefit10': 'x3 Outdoor Sessions Weekly',
      'membership.academyPlan.fullSeason.benefit11': 'Access To Our Indoor Performance Hub',
      'membership.academyPlan.fullSeason.benefit12': 'Competitive Fixtures And Tournaments',
      'membership.academyPlan.fullSeason.benefit13': 'Alignment And Relationships With World-Wide Clubs',
      'membership.academyPlan.fullSeason.benefit14': 'Talent Identification Opportunities Throughout Our Pathway',
      'membership.academyPlan.fullSeason.benefit15': 'Nutrition / Sport Psychology / Sports Science Monitoring',
      'membership.academyPlan.fullSeason.benefit16': 'SAFF & England National Team Standard Analysis Systems And Softwares',
      'membership.academyPlan.fullSeason.benefit17': 'Organised Schedule To Allow For Male And Female Sessions',
      'membership.academyPlan.fullSeason.benefit18': 'Mixture Of Male And Female Staff To Accommodate All',
      'membership.academyPlan.fullSeason.benefit19': 'Holistic Individual Development Plans',
      'membership.academyPlan.quarterly.title': 'QUARTERLY OPTION',
      'membership.academyPlan.quarterly.description': 'A flexible option with limited benefits compared to the full season membership.',
      'membership.academyPlan.private.title': '1-2-1 PRIVATE TECHNICAL COACHING',
      'membership.academyPlan.private.benefit1': 'High-intensity personalized development',
      'membership.academyPlan.private.benefit2': 'Aligned to player\'s individual development plan',
      'membership.academyPlan.private.benefit3': 'Position-specific drills',
      'membership.academyPlan.private.benefit4': 'Video analysis (optional add-on)',
      'membership.academyPlan.family.tag': 'FAMILY PACKAGE',
      'membership.academyPlan.family.title': '2 ADULT X 2 CHILDREN',
      'membership.academyPlan.family.description': 'A bundled package designed for families training together at Vision7.',
      'membership.academyPlan.family.benefit1': '2 Adults Gym Membership',
      'membership.academyPlan.family.benefit2': '2 Children Academy Membership',
      'membership.academyPlan.family.benefit3': '1x Padel Booking Monthly',
      'membership.academyPlan.family.benefit4': 'Free Birthday Party',
      'membership.academyPlan.family.benefit5': 'x2 PT Sessions',
      'membership.academyPlan.family.benefit6': 'x2 Private Technical Coaching Sessions',
      'membership.academyPlan.miniKickers.title': 'MINI KICKERS - 3 MONTHS',
      'membership.academyPlan.miniKickers.description': '2 Sessions per week for 3 months',
      'enquiry.personalInformation': 'PERSONAL INFORMATION',
      'enquiry.playerDetails': 'PLAYER DETAILS',
      'enquiry.orDateOfBirth': 'Or Date of Birth',
      'profile.fullName': 'Full Name',
      'profile.email': 'Email',
      'profile.phone': 'Phone',
      'profile.city': 'City',
      'common.soon': 'SOON',
    },  // end 'en'
    'ar': {
      // Common
      'common.loading': 'جاري التحميل...',
      'common.error': 'خطأ',
      'common.cancel': 'إلغاء',
      'common.back': 'رجوع',
      'common.noResults': 'لا توجد نتائج',
      'common.bookNow': 'احجز الآن',
      'common.exploreMembership': 'استكشف العضوية',
      'common.enquireNow': 'استفسر الآن',
      'common.save': 'حفظ',
      'common.delete': 'حذف',
      'common.confirm': 'تأكيد',
      'common.success': 'نجح',
      'common.retry': 'إعادة المحاولة',
      'common.ok': 'موافق',
      'common.share': 'مشاركة',
      'common.viewBookings': 'عرض حجوزاتي',
      'common.idToken': 'رمز الهوية',

      // Auth
      'auth.loginTitle': 'مرحباً بعودتك',
      'auth.loginSubtitle': 'تسجيل الدخول إلى حساب Vision7',
      'auth.email': 'البريد الإلكتروني',
      'auth.password': 'كلمة المرور',
      'auth.signIn': 'تسجيل الدخول',
      'auth.signInWithBiometrics': 'تسجيل الدخول بالبصمة',
      'auth.forgotPassword': 'نسيت كلمة المرور؟',
      'auth.resetPassword': 'إعادة تعيين كلمة المرور',
      'auth.noAccount': 'ليس لديك حساب؟',
      'auth.hasAccount': 'لديك حساب بالفعل؟',
      'auth.signUp': 'إنشاء حساب',
      'auth.agreeToPrefix': 'أوافق على ',
      'auth.agreeToMiddle': ' و ',
      'auth.mustAgreeToTerms': 'يرجى الموافقة على شروط الخدمة وسياسة الخصوصية للمتابعة',
      'auth.validation.emailRequired': 'البريد الإلكتروني مطلوب',
      'auth.validation.emailInvalid': 'عنوان بريد إلكتروني غير صالح',
      'auth.validation.passwordRequired': 'كلمة المرور مطلوبة',
      'auth.validation.passwordMinLength': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
      'auth.validation.nameRequired': 'الاسم مطلوب',
      'auth.logout': 'تسجيل الخروج',
      'auth.logoutConfirm': 'هل أنت متأكد من تسجيل الخروج؟',
      'auth.deleteAccount': 'حذف الحساب',
      'auth.deleteAccountConfirm': 'سيؤدي هذا إلى حذف حسابك وبياناتك الشخصية نهائيًا. لا يمكن التراجع عن هذا. هل أنت متأكد؟',
      'auth.deleteAccountFailed': 'تعذر حذف حسابك. يرجى المحاولة مرة أخرى.',
      'auth.googleFailed': 'فشل تسجيل الدخول عبر جوجل. يرجى المحاولة مرة أخرى.',
      'auth.appleFailed': 'فشل تسجيل الدخول عبر آبل. يرجى المحاولة مرة أخرى.',
      'auth.google': 'جوجل',
      'auth.apple': 'آبل',
      'auth.orContinueWith': 'أو استمر بـ',
      'auth.orSignInWith': 'أو سجل الدخول بـ',
      'auth.googleSignIn': 'تسجيل الدخول بجوجل',
      'auth.appleSignIn': 'تسجيل الدخول بآبل',
      'auth.emailHint': 'بريدك@example.com',
      'auth.passwordHint': 'أدخل كلمة المرور',
      'auth.confirmPasswordHint': 'أدخل كلمة المرور',

      // Register
      'register.title': 'إنشاء حساب',
      'register.subtitle': 'انضم إلى Vision7 اليوم',
      'register.name': 'الاسم الكامل',
      'register.email': 'البريد الإلكتروني',
      'register.password': 'كلمة المرور',
      'register.confirmPassword': 'تأكيد كلمة المرور',
      'register.phone': 'رقم الهاتف (اختياري)',
      'register.gender': 'الجنس (اختياري)',
      'register.createAccount': 'إنشاء الحساب',
      'register.nameHint': 'أدخل اسمك الكامل',
      'register.emailHint': 'بريدك@example.com',
      'register.passwordHint': 'أدخل كلمة المرور',

      // Forgot Password
      'forgot.title': 'إعادة تعيين كلمة المرور',
      'forgot.subtitle': 'أدخل بريدك الإلكتروني لتلقي تعليمات إعادة التعيين',
      'forgot.sendLink': 'إرسال رابط إعادة التعيين',
      'forgot.sent': 'تحقق من بريدك الإلكتروني لتعليمات إعادة التعيين',
      'forgot.emailHint': 'بريدك@example.com',
      'forgot.backToLogin': 'العودة لتسجيل الدخول',

      // Onboarding
      'onboarding.welcome': 'مرحباً بك في Vision7',
      'onboarding.title': 'VISION7',
      'onboarding.subtitle': 'وجهتك المتميزة للرفاهية والرياضة',
      'onboarding.next': 'التالي',
      'onboarding.getStarted': 'ابدأ',
      'onboarding.skip': 'تخطي',

      // Home
      'home.title': 'مرحباً بك في Vision7\nLeisure',
      'home.subtitle': 'تجربتك المتميزة للرفاهية والرياضة',
      'home.greeting.morning': 'صباح الخير',
      'home.greeting.afternoon': 'مساء الخير',
      'home.greeting.evening': 'مساء الخير',
      'home.experiencesTitle': 'التجارب',
      'home.focusAreasTitle': 'ما يميزنا',
      'home.bookATour': 'احجز جولة',
      'home.exploreMore': 'استكشف المزيد',
      'home.viewAll': 'عرض الكل',
      'home.experience.padel': 'بادل',
      'home.experience.football5': '5 لاعبين',
      'home.experience.football7': '7 لاعبين',
      'home.experience.football9': '9 لاعبين',
      'home.experience.football11': '11 لاعب',
      'home.experience.v7arena': 'V7 أرينا',
      'home.experience.birthday': 'حفلات الأعياد',
      'home.experience.padel.subtitle': 'ملاعب عالمية المستوى',
      'home.experience.football.subtitle': 'احجز ملعب',
      'home.experience.football11.subtitle': 'ملعب كامل',
      'home.experience.football9.subtitle': 'ملعب ذكي 3 ضد 3',
      'home.experience.gym': 'الجيم',
      'home.experience.gym.subtitle': 'مجهز بالكامل',
      'home.experience.swimming': 'السباحة',
      'home.experience.swimming.subtitle': 'حمام سباحة',
      'home.experience.wellness': 'العافية',
      'home.experience.wellness.subtitle': 'سبا واستشفاء',
      'home.experience.rooftop': 'السطح',
      'home.experience.rooftop.subtitle': 'صالة وإطلالات',
      'home.experience.community': 'المجتمع',
      'home.experience.community.subtitle': 'فعاليات ومناسبات',
      'home.experience.comingSoon': 'قريباً',
      'home.experience.birthday.subtitle': 'باقات متاحة',
      'home.focusArea.premium': 'جودة عالية',
      'home.focusArea.coaches': 'مدربون محترفون',
      'home.focusArea.booking': 'حجز سهل',

      // Academy
      'academy.home.title': 'مرحباً بك في Vision7\nكرة القدم',
      'academy.pillar.passion': 'الشغف',
      'academy.pillar.excellence': 'التميز',
      'academy.pillar.integrity': 'النزاهة',
      'academy.pillar.community': 'المجتمع',
      'academy.pillar.coaching': 'كرة القدم',
      'academy.pillar.coaching.subtitle': 'تدريب معتمد من UEFA وAFC.',
      'academy.pillar.development': 'التطوير',
      'academy.pillar.development.subtitle': 'التعليم، الرعاية، أسلوب الحياة',
      'academy.pillar.competition': 'الأداء',
      'academy.pillar.competition.subtitle': 'علوم الرياضة والأداء البدني',
      'academy.about.title': 'كرة القدم\nالعضوية',
      'academy.programs': 'البرامج',
      'academy.facilities': 'المرافق',
      'academy.coaches': 'المدربون',
      'academy.events': 'الفعاليات',
      'academy.contact': 'اتصل بنا',
      'academy.register': 'التسجيل',
      'academy.registerCta': 'سجل اهتمامك',
      'academy.register.hint.fullName': 'الاسم الكامل',
      'academy.register.hint.parentName': 'الاسم الكامل',
      'academy.register.hint.age': 'العمر',
      'academy.register.hint.program': 'اختر البرنامج',
      'academy.quickLink.programs': 'البرامج',
      'academy.quickLink.facilities': 'المرافق',
      'academy.quickLink.coaches': 'المدربون',
      'academy.quickLink.events': 'الفعاليات',
      'academy.quickLink.contact': 'اتصل بنا',
      'academy.quickLink.register': 'التسجيل',

      // Explore
      'explore.title': 'استكشاف',
      'explore.search': 'البحث عن المرافق...',
      'explore.all': 'الكل',
      'explore.noResults': 'لم يتم العثور على مرافق',
      'explore.filterBy': 'تصفية حسب الفئة',
      'explore.category.padel': 'مركز الأداء الداخلي',
      'explore.category.padel.leisure': 'بادل',
      'explore.category.gym': 'الجيم',
      'explore.category.wellness': 'العافية',
      'explore.category.rooftop': 'السطح',
      'explore.category.swimming': 'السباحة',
      'explore.swimming.beginner': 'برنامج المبتدئين',
      'explore.swimming.beginner.sub': 'تعلم السلامة المائية ومهارات السباحة الأساسية.',
      'explore.swimming.technique': 'تطوير التقنية',
      'explore.swimming.technique.sub': 'تحسين تقنية السباحة والتحكم في التنفس.',
      'explore.swimming.junior': 'سباحة الناشئين',
      'explore.swimming.junior.sub': 'تطوير منظم للسباحين الصغار.',
      'explore.swimming.performance': 'فريق الأداء',
      'explore.swimming.performance.sub': 'تدريب متقدم للسباحين التنافسيين.',
      'explore.swimming.coaching': 'تدريب خاص',
      'explore.swimming.coaching.sub': 'جلسات فردية مع مدربي سباحة معتمدين.',
      'explore.swimming.adult': 'تدريب سباحة للبالغين',
      'explore.swimming.adult.sub': 'بناء الثقة وتحسين القدرة على التحمل.',
      'explore.wellness.heading': 'رحلة العافية',
      'explore.wellness.subtitle': 'استمتع برحلة عافية شاملة مصممة خصيصاً للاسترخاء وتجديد الحيوية.',
      'explore.wellness.hydrotherapy': 'العلاج المائي',
      'explore.wellness.hydrotherapy.sub': 'أحواض مائية منشطة',
      'explore.wellness.spa': 'سبا',
      'explore.wellness.spa.sub': 'سبا فاخر منسق',
      'explore.wellness.sauna': 'ساونا',
      'explore.wellness.sauna.sub': 'ساونا بأحدث التقنيات',
      'explore.wellness.coldPlunge': 'الغطس البارد',
      'explore.wellness.coldPlunge.sub': 'غطس بارد منعش',
      'explore.wellness.treatments': 'العلاجات',
      'explore.wellness.treatments.sub': 'علاج شخصي',
      'explore.wellness.therapists': 'المعالجون',
      'explore.wellness.therapists.sub': 'معالجون ذوو خبرة',
      'explore.comingSoon': 'قريباً',
      'explore.padelCourt.name': 'ملعب بادل',
      'explore.padelCourt.sessionLength': 'مدة الجلسة',
      'explore.padelCourt.mins': 'دقيقة',
      'explore.padelCourt.bookACourt': 'احجز ملعباً',
      'explore.padelCourt.facilitiesHeading': 'مرافق البادل',
      'explore.padelCourt.facility.courts': 'ملاعب متميزة',
      'explore.padelCourt.facility.courts.sub': 'ملاعب عالية الجودة',
      'explore.padelCourt.facility.towels': 'خدمة المناشف',
      'explore.padelCourt.facility.towels.sub': 'مناشف مجانية',
      'explore.padelCourt.facility.refreshments': 'المرطبات',
      'explore.padelCourt.facility.refreshments.sub': 'مشروبات ووجبات خفيفة',
      'explore.padelCourt.facility.lounge': 'صالة اللاعبين',
      'explore.padelCourt.facility.lounge.sub': 'صالة اجتماعية',
      'explore.padelCourt.facility.coaching': 'تدريب خاص',
      'explore.padelCourt.facility.coaching.sub': 'إرشاد من الخبراء',
      'explore.padelCourt.facility.memberships': 'عضويات البادل',
      'explore.padelCourt.facility.memberships.sub': 'مزايا حصرية للأعضاء',
      'explore.gym.poweredBy': 'مدعوم من',
      'explore.gym.heading': 'بيئة التدريب',
      'explore.gym.subtitle': 'تدرب بجدية أكبر. تعافَ بشكل أفضل.',
      'explore.gym.feature1': 'أحدث معدات تكنوجيم',
      'explore.gym.feature2': 'برامج تدريب مدعومة بالذكاء الاصطناعي',
      'explore.gym.feature3': 'تدريب شخصي',
      'explore.gym.amenity.gymAccess': 'دخول الجيم',
      'explore.gym.amenity.steam': 'حمام بخار',
      'explore.gym.amenity.sauna': 'ساونا',
      'explore.gym.amenity.jacuzzi': 'جاكوزي',
      'explore.gym.amenity.pool': 'مسبح',
      'explore.gym.membershipsHeading': 'عضويات الجيم',
      'explore.gym.plan.oneMonth': 'شهر واحد',
      'explore.gym.plan.threeMonths': '3 أشهر',
      'explore.gym.plan.sixMonths': '6 أشهر',
      'explore.gym.plan.annual': 'باقة سنوية للصحة والترفيه',
      'explore.gym.plan.dailyPass': 'بطاقة يومية',
      'explore.package.oneMonthAdult': 'شهر واحد - بالغين',
      'explore.package.oneMonthJunior': 'شهر واحد - ناشئين',
      'explore.package.threeMonthAdult': '3 أشهر - بالغين',
      'explore.package.threeMonthJunior': '3 أشهر - ناشئين',
      'explore.package.benefit1': 'ساعة وصول يومي لجميع المناطق',
      'explore.package.benefit2': 'وصول مشترك لـ Smart Pitch (حسب التوفر)',
      'explore.category.football': 'حجز المرافق',
      'explore.football.feature1': 'عشب معتمد من الفيفا',
      'explore.football.feature2': 'معدات أوروبية عالمية المستوى',
      'explore.football.feature3': 'إضاءة استاد',
      'explore.football.feature4': 'غرف تبديل الملابس والاستحمام',
      'explore.football.feature5': 'الوصول إلى صالة السطح',
      'explore.football.feature6': 'مياه معبأة مجانية',
      'explore.football.package5': '5 لاعبين',
      'explore.football.package7': '7 لاعبين',
      'explore.football.package9': '9 لاعبين',
      'explore.football.package11': '11 لاعب',
      'explore.football.duration60': '60 دقيقة',
      'explore.football.duration90': '90 دقيقة',
      'explore.football.duration2h': 'ساعتان',
      'explore.category.v7arena': 'V7 أرينا',
      'explore.arena.feature1': 'منطقة الواقع الافتراضي والألعاب',
      'explore.arena.feature2': 'اختبار قوة التسديد',
      'explore.arena.feature3': 'دوائر الدقة',
      'explore.arena.feature4': 'تقنية بيانات الأداء',
      'explore.arena.feature5': 'غرفة التحليل التكتيكي',
      'explore.arena.membersGame': 'مباراة 3 ضد 3: أعضاء',
      'explore.arena.nonMembersGame': 'مباراة 3 ضد 3: غير أعضاء',
      'explore.arena.gameDuration': '45 دقيقة مع مدرب وإضاءة',
      'explore.category.birthday': 'حفلات عيد الميلاد',
      'explore.birthday.packageName': 'باقات أعياد الميلاد',
      'explore.birthday.packageDesc': 'حفلة ساعتان: استخدام خاص كامل، مرطبات، طعام وشهادة عيد ميلاد',
      'explore.category.other': 'أخرى',

      // Booking
      'booking.title': 'حجز المرفق',
      'booking.confirm': 'تأكيد الحجز',
      'booking.yourDetails': 'تفاصيلك',
      'booking.name': 'الاسم الكامل',
      'booking.email': 'البريد الإلكتروني',
      'booking.phone': 'رقم الهاتف',
      'booking.date': 'التاريخ',
      'booking.time': 'الوقت',
      'booking.facility': 'المرفق',
      'booking.price': 'السعر',
      'booking.guests': 'الضيوف',
      'booking.status': 'الحالة',
      'booking.confirmed': 'مؤكد',
      'booking.pending': 'قيد الانتظار',
      'booking.cancelled': 'ملغى',
      'booking.confirmationTitle': 'تم تأكيد الحجز!',
      'booking.confirmationMsg': 'تم تأكيد حجزك بنجاح',
      'booking.share': 'مشاركة',
      'booking.close': 'إغلاق',
      'booking.qrCode': 'عرض رمز الاستجابة السريعة',
      'booking.id': 'رقم الحجز',
      'booking.total': 'الإجمالي',
      'booking.detail.title': 'تفاصيل الحجز',
      'booking.facilityNotFound': 'المرفق غير موجود',
      'booking.notFound': 'الحجز غير موجود',
      'booking.priceFormat': '{price} ريال / {duration}دقيقة',
      'booking.pricePerSlot': '{price} ريال',
      'booking.slotDuration': '{duration} دقيقة',

      // Bookings
      'bookings.title': 'حجوزاتي',
      'bookings.upcoming': 'القادمة',
      'bookings.past': 'السابقة',
      'bookings.noBookings': 'لا توجد حجوزات بعد',
      'bookings.noBookingsSubtitle': 'استكشف المرافق واجعل أول حجز لك',
      'bookings.cancelled': 'ملغى',
      'bookings.noUpcoming': 'لا توجد حجوزات قادمة',
      'bookings.noPast': 'لا توجد حجوزات سابقة',
      'bookings.idLabelAr': 'رقم الحجز',

      // Facility
      'facility.amenities': 'المرافق',
      'facility.hours': 'ساعات العمل',
      'facility.notFound': 'المركز الرياضي غير موجود',

      // Calendar
      'calendar.day.1': 'أحد',
      'calendar.day.2': 'إثنين',
      'calendar.day.3': 'ثلاثاء',
      'calendar.day.4': 'أربعاء',
      'calendar.day.5': 'خميس',
      'calendar.day.6': 'جمعة',
      'calendar.day.7': 'سبت',
      'calendar.month.1': 'يناير',
      'calendar.month.2': 'فبراير',
      'calendar.month.3': 'مارس',
      'calendar.month.4': 'أبريل',
      'calendar.month.5': 'مايو',
      'calendar.month.6': 'يونيو',
      'calendar.month.7': 'يوليو',
      'calendar.month.8': 'أغسطس',
      'calendar.month.9': 'سبتمبر',
      'calendar.month.10': 'أكتوبر',
      'calendar.month.11': 'نوفمبر',
      'calendar.month.12': 'ديسمبر',

      // Tab Bar
      'tab.home': 'الرئيسية',
      'tab.explore': 'استكشاف',
      'tab.bookings': 'حجوزاتي',
      'tab.membership': 'العضوية',
      'tab.profile': 'الملف الشخصي',

      // Home
      'home.tourSubtitle': 'تعرف على منشآتنا عن قرب',

      // Membership
      'membership.title': 'العضوية',
      'membership.active': 'الخطة النشطة',
      'membership.invoices': 'الفواتير',
      'membership.plans': 'الخطط المتاحة',
      'membership.enquire': 'استفسر',
      'membership.subscribe': 'اشترك',
      'membership.invoiceDetail': 'تفاصيل الفاتورة',
      'membership.invoiceItems': 'البنود',
      'membership.invoiceTotal': 'الإجمالي',
      'membership.invoiceDate': 'التاريخ',
      'membership.invoiceStatus': 'الحالة',
      'membership.invoicePaid': 'مدفوع',
      'membership.invoicePending': 'قيد الانتظار',
      'membership.noInvoices': 'لا توجد فواتير بعد',
      'membership.activePlan': 'الخطة النشطة',
      'membership.noActive': 'لا توجد عضوية نشطة',
      'membership.validUntil': 'صالح حتى',
      'membership.upgrade': 'ترقية',
      'membership.availablePlans': 'الخطط المتاحة',
      'membership.history': 'السجل',
      'membership.noPlans': 'لا توجد خطط متاحة',
      'membership.plan.gold': 'عضوية ذهبية',
      'membership.period.month': 'شهر',
      'membership.period.day': 'يوم',

      // Profile
      'profile.title': 'الملف الشخصي',
      'profile.account': 'الحساب',
      'profile.preferences': 'التفضيلات',
      'profile.about': 'حول',
      'profile.bookings': 'حجوزاتي',
      'profile.membership': 'العضوية',
      'profile.invoices': 'الفواتير',
      'profile.accessPass': 'بطاقة الدخول',
      'profile.notifications': 'الإشعارات',
      'profile.language': 'اللغة',
      'profile.languageCurrent': 'English',
      'accessPass.title': 'بطاقة الدخول',
      'accessPass.showAtDoor': 'أظهر هذا الرمز لأي قارئ أبواب في فيجن 7',
      'accessPass.validUntil': 'صالحة حتى',
      'accessPass.expired': 'منتهية الصلاحية',
      'accessPass.noPass': 'لا توجد بطاقة نشطة',
      'accessPass.noPassBody':
          'ستظهر بطاقة دخول برمز QR هنا بمجرد أن يصدرها الموظفون لعضويتك أو حجزك.',
      'common.somethingWentWrong': 'حدث خطأ ما',
      'profile.languageOptionEn': 'English',
      'profile.languageOptionAr': 'العربية',
      'profile.mode': 'الوضع',
      'profile.leisureMode': 'ترفيه',
      'profile.academyMode': 'أكاديمي',
      'profile.privacyPolicy': 'سياسة الخصوصية',
      'profile.termsOfService': 'شروط الخدمة',
      'profile.aboutApp': 'عن Vision7',
      'profile.version': 'الإصدار',
      'profile.guestUser': 'زائر',
      'profile.memberSince': 'عضو منذ',
      'profile.failedToLoad': 'فشل تحميل الملف الشخصي',
      'profile.editProfile': 'تعديل الملف الشخصي',

      // Enquiry
      'enquiry.title': 'استفسار',
      'enquiry.subtitle': 'أخبرنا عن احتياجاتك',
      'enquiry.membershipType': 'نوع العضوية',
      'enquiry.fitnessGoal': 'الهدف اللياقي',
      'enquiry.experience': 'مستوى الخبرة',
      'enquiry.preferredTime': 'الوقت المفضل',
      'enquiry.howHeard': 'كيف سمعت عنا؟',
      'enquiry.message': 'الرسالة',
      'enquiry.hint.name': 'الاسم الكامل',
      'enquiry.hint.message': 'أخبرنا المزيد...',
      'enquiry.submit': 'إرسال الاستفسار',
      'enquiry.success': 'تم إرسال الاستفسار بنجاح!',

      // Tour Booking
      'tourBooking.title': 'احجز جولة',
      'tourBooking.subtitle': 'جدولة زيارتك إلى Vision7',
      'tourBooking.selectDate': 'اختر التاريخ',
      'tourBooking.selectTime': 'اختر الوقت',
      'tourBooking.yourInfo': 'معلوماتك',
      'tourBooking.interests': 'مجالات الاهتمام',
      'tourBooking.confirm': 'تأكيد الحجز',
      'tourBooking.success': 'تم حجز الجولة بنجاح!',
      'tour.hint.name': 'الاسم الكامل',

      // Notifications
      'notifications.title': 'الإشعارات',
      'notifications.noNotifications': 'لا توجد إشعارات بعد',
      'notifications.markAllRead': 'تحديد الكل كمقروء',
      'notifications.justNow': 'الآن',

      // Facility Detail
      'facilityDetail.amenities': 'المرافق',
      'facilityDetail.hours': 'ساعات العمل',
      'facilityDetail.description': 'الوصف',
      'facilityDetail.bookNow': 'احجز الآن',
      'facilityDetail.availableSlots': 'الأوقات المتاحة',
      'facilityDetail.noSlots': 'لا توجد أوقات متاحة',
      'facilityDetail.genderRule': 'قاعدة الجنس',
      'facilityDetail.mixed': 'مختلط',
      'facilityDetail.maleOnly': 'ذكور فقط',
      'facilityDetail.femaleOnly': 'إناث فقط',
      'facilityDetail.pricePerSlot': 'لكل فترة',
      'facilityDetail.duration': 'المدة',
      // --- Auto-added: missing keys sweep ---
      'academy.about.subtitle': 'أكاديمية كرة القدم الرائدة في الرياض',
      'academy.about.missionTitle': 'مهمتنا',
      'academy.about.mission': 'رعاية الجيل القادم من أبطال كرة القدم من خلال الجمع بين التميز الفني وبناء الشخصية.',
      'academy.about.intro': 'تكرّس أكاديمية فيجن7 جهودها لتطوير المواهب الشابة في كرة القدم من خلال تدريب عالمي المستوى ومرافق متطورة ومسار تطوير منظم.',
      'academy.about.stats': 'بالأرقام',
      'academy.about.players': 'لاعبون',
      'academy.about.coaches': 'مدربون',
      'academy.about.trophies': 'بطولات',
      'academy.coaches.title': 'مدربونا',
      'academy.coaches.subtitle': 'طاقم تدريبي معتمد وذو خبرة',
      'academy.coaches.role': 'الدور',
      'academy.coaches.experience': 'الخبرة',
      'academy.contact.title': 'تواصل معنا',
      'academy.contact.subtitle': 'تواصل مع فريق الأكاديمية',
      'academy.contact.call': 'اتصل بنا',
      'academy.contact.email': 'أرسل بريدًا إلكترونيًا',
      'academy.contact.hours': 'الأحد - الخميس: 8 صباحًا - 10 مساءً',
      'academy.events.title': 'الفعاليات',
      'academy.events.subtitle': 'البطولات والمعسكرات والعروض',
      'academy.facilities.title': 'مرافق الأكاديمية',
      'academy.facilities.subtitle': 'مرافق تدريب عالمية المستوى',
      'academy.home.aboutText': '2026/27',
      'academy.home.quickLinks': 'روابط سريعة',
      'academy.programs.title': 'البرامج',
      'academy.programs.subtitle': 'اختر البرنامج المناسب لمستواك',
      'academy.register.title': 'التسجيل في الأكاديمية',
      'academy.register.subtitle': 'ابدأ رحلتك في الأكاديمية',
      'academy.register.playerName': 'اسم اللاعب',
      'academy.register.parentName': 'اسم ولي الأمر',
      'academy.register.age': 'عمر اللاعب',
      'academy.register.phone': 'رقم الهاتف',
      'academy.register.program': 'البرنامج',
      'academy.register.submit': 'إرسال التسجيل',
      'academy.register.success': 'تم إرسال التسجيل بنجاح!',
      'academy.title': 'وضع الأكاديمية',
      'auth.backToLogin': 'العودة لتسجيل الدخول',
      'auth.confirmPassword': 'تأكيد كلمة المرور',
      'auth.createAccount': 'إنشاء حساب',
      'auth.forgotPasswordSubtitle': 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين',
      'auth.forgotPasswordTitle': 'نسيت كلمة المرور؟',
      'auth.fullName': 'الاسم الكامل',
      'auth.haveAccount': 'لديك حساب بالفعل؟ ',
      'auth.nameHint': 'أدخل اسمك الكامل',
      'auth.registerSubtitle': 'انضم إلى فيجن7 اليوم',
      'auth.resetLinkSent': 'تم إرسال رابط إعادة التعيين!',
      'auth.resetLinkSentSubtitle': 'تحقق من بريدك الإلكتروني للحصول على تعليمات إعادة التعيين',
      'auth.sendResetLink': 'إرسال رابط إعادة التعيين',
      'auth.validation.confirmPasswordRequired': 'يرجى تأكيد كلمة المرور',
      'auth.validation.fullNameRequired': 'يرجى إدخال اسمك الكامل',
      'auth.validation.passwordMismatch': 'كلمتا المرور غير متطابقتين',
      'booking.cancel.confirm': 'هل أنت متأكد أنك تريد إلغاء هذا الحجز بتاريخ {date}؟',
      'booking.cancel.label': 'إلغاء الحجز',
      'booking.cancel.title': 'إلغاء الحجز',
      'booking.confirmation.facility': 'المرفق',
      'booking.confirmation.message': 'تم تأكيد حجزك.',
      'booking.continue': 'متابعة',
      'booking.defaultFacilityTitle': 'حجز المرفق',
      'booking.error': 'فشل الحجز. يرجى المحاولة مرة أخرى.',
      'booking.notes': 'طلبات خاصة...',
      'common.done': 'تم',
      'common.no': 'لا',
      'common.select': 'اختر خيارًا',
      'common.yes': 'نعم',
      'enquiry.city': 'المدينة / المنطقة',
      'enquiry.currentLevel': 'المستوى الحالي',
      'enquiry.email': 'البريد الإلكتروني',
      'enquiry.enquiringFor': 'الاستفسار من أجل',
      'enquiry.error': 'فشل إرسال الاستفسار. يرجى المحاولة مرة أخرى.',
      'enquiry.fullName': 'الاسم الكامل',
      'enquiry.gender': 'الجنس',
      'enquiry.goal': 'الهدف',
      'enquiry.hint.age': 'العمر',
      'enquiry.hint.city': 'مثال: الرياض',
      'enquiry.hint.fullName': 'اسمك الكامل',
      'enquiry.hint.medicalNotes': 'أي إصابات أو حالات صحية أو حساسية يجب أن نكون على علم بها',
      'enquiry.hint.playerName': 'الاسم الكامل للاعب',
      'enquiry.hint.preferredDays': 'مثال: أمسيات أيام الأسبوع، صباح عطلة نهاية الأسبوع',
      'enquiry.howDidYouHear': 'كيف سمعت عنا؟',
      'enquiry.language': 'اللغة المفضلة',
      'enquiry.medicalNotes': 'ملاحظات طبية (اختياري)',
      'enquiry.phone': 'الهاتف *',
      'enquiry.playerAge': 'عمر اللاعب',
      'enquiry.playerName': 'اسم اللاعب',
      'enquiry.preferredDays': 'الأيام / الأوقات المفضلة',
      'enquiry.preferredProgram': 'البرنامج المفضل',
      'enquiry.regarding': 'الاستفسار بخصوص',
      'enquiry.submitted': 'تم إرسال الاستفسار بنجاح!',
      'invoices.detail': 'تفاصيل الفاتورة',
      'invoices.lineItems': 'بنود الفاتورة',
      'invoices.none': 'لا توجد فواتير بعد',
      'invoices.number': 'فاتورة',
      'invoices.payment': 'الدفع',
      'invoices.title': 'الفواتير',
      'membership.endDate': 'تاريخ الانتهاء',
      'membership.familyMembers': 'أفراد العائلة',
      'membership.loadFailed': 'فشل تحميل بيانات العضوية',
      'membership.renewsIn': 'يتجدد خلال {n} يومًا',
      'membership.renewsToday': 'يتجدد اليوم',
      'membership.startDate': 'تاريخ البدء',
      'membership.status.active': 'نشط',
      'membership.status.cancelled': 'ملغى',
      'membership.status.expired': 'منتهي',
      'membership.status.frozen': 'مجمّد',
      'membership.status.pending': 'قيد الانتظار',
      'payment.confirm': 'تأكيد والدفع',
      'payment.confirmMessage': 'شراء {plan} مقابل {price}؟',
      'payment.confirmTitle': 'تأكيد الشراء',
      'payment.failed': 'فشلت عملية الدفع. يرجى المحاولة مرة أخرى.',
      'payment.method': 'طريقة الدفع',
      'payment.selectMethod': 'اختر طريقة الدفع',
      'payment.success': 'تم الدفع بنجاح! تم تفعيل العضوية.',
      'profile.myBookings': 'حجوزاتي',
      'profile.updated': 'تم تحديث الملف الشخصي',
      'settings.language': 'اللغة',
      'settings.mode': 'الوضع',
      'settings.title': 'الإعدادات',
      'tour.availableTimes': 'الأوقات المتاحة',
      'tour.confirm': 'تأكيد حجز الجولة',
      'tour.confirmed': 'تم حجز الجولة بتاريخ {date} الساعة {time}',
      'tour.email': 'البريد الإلكتروني',
      'tour.error': 'فشل حجز الجولة. يرجى المحاولة مرة أخرى.',
      'tour.eyebrow.academy': 'أكاديمية فيجن7',
      'tour.eyebrow.leisure': 'فيجن7 للترفيه',
      'tour.female': 'أنثى',
      'tour.female.hours': '6 صباحًا – 3 عصرًا',
      'tour.left': 'متبقٍ',
      'tour.male': 'ذكر',
      'tour.male.hours': '4 عصرًا – 1 صباحًا',
      'tour.name': 'الاسم الكامل',
      'tour.noSlots': 'لا توجد أوقات متاحة لهذه الفترة',
      'tour.phone': 'رقم الهاتف',
      'tour.phoneHint': 'رقم الهاتف يتيح لنا تأكيد زيارتك.',
      'tour.pickTimeToContinue': 'اختر وقتًا للمتابعة',
      'tour.step1': '1 · اختر تاريخًا',
      'tour.subtitle': 'شاهد صالة الألعاب الرياضية والمسبح وملاعب البادل ومساحات العافية بنفسك. اختر يومًا ووقتًا وسيقوم فريقنا بجولة شخصية لك.',
      'tour.title': 'جولة في نادي الترفيه',
      'tour.title.academy': 'جولة في الأكاديمية',
      'validation.ageRange': 'يجب أن يكون العمر بين 5 و25 عامًا',
      'validation.emailInvalid': 'بريد إلكتروني غير صالح',
      'validation.required': 'مطلوب',
      'booking.detail.failedToLoad': 'فشل تحميل الحجز',
      'bookings.idLabelEn': 'رقم الحجز',
      'membership.academyPlan.fullSeason.tag': 'الأفضل قيمة',
      'membership.academyPlan.fullSeason.title': 'الموسم الكامل',
      'membership.academyPlan.fullSeason.benefit1': 'ممارسون رائدون عالميًا',
      'membership.academyPlan.fullSeason.benefit2': 'مدربون معتمدون من الاتحاد الأوروبي لكرة القدم، بخبرة في أندية الدوري الإنجليزي الممتاز',
      'membership.academyPlan.fullSeason.benefit3': 'معدات أوروبية متطورة، من أحد 5 موزعين معتمدين من الفيفا في العالم',
      'membership.academyPlan.fullSeason.benefit4': 'ملاعب بمقاسات الفيفا',
      'membership.academyPlan.fullSeason.benefit5': 'إضاءة متطورة على طراز الملاعب',
      'membership.academyPlan.fullSeason.benefit6': 'جميع الموظفين تم فحصهم بدقة ومعتمدون في الحماية والإسعافات الأولية',
      'membership.academyPlan.fullSeason.benefit7': 'رئيس القسم الطبي وفريق علاج طبيعي مؤهل بالكامل',
      'membership.academyPlan.fullSeason.benefit8': 'غرفة طبية مجهزة بالكامل بمعدات الطوارئ في الموقع',
      'membership.academyPlan.fullSeason.benefit9': 'خطة طوارئ في جميع أنحاء الموقع',
      'membership.academyPlan.fullSeason.benefit10': '3 جلسات خارجية أسبوعيًا',
      'membership.academyPlan.fullSeason.benefit11': 'الوصول إلى مركز الأداء الداخلي',
      'membership.academyPlan.fullSeason.benefit12': 'مباريات وبطولات تنافسية',
      'membership.academyPlan.fullSeason.benefit13': 'شراكات وعلاقات مع أندية عالمية',
      'membership.academyPlan.fullSeason.benefit14': 'فرص اكتشاف المواهب طوال مسارنا التطويري',
      'membership.academyPlan.fullSeason.benefit15': 'متابعة التغذية / علم النفس الرياضي / علوم الرياضة',
      'membership.academyPlan.fullSeason.benefit16': 'أنظمة وبرمجيات تحليل بمعايير الاتحاد السعودي والمنتخب الإنجليزي',
      'membership.academyPlan.fullSeason.benefit17': 'جدول منظم يتيح جلسات للذكور والإناث',
      'membership.academyPlan.fullSeason.benefit18': 'طاقم من الذكور والإناث لتلبية احتياجات الجميع',
      'membership.academyPlan.fullSeason.benefit19': 'خطط تطوير فردية شاملة',
      'membership.academyPlan.quarterly.title': 'الخيار الفصلي',
      'membership.academyPlan.quarterly.description': 'خيار مرن بمزايا محدودة مقارنة بعضوية الموسم الكامل.',
      'membership.academyPlan.private.title': 'تدريب فني خاص فردي',
      'membership.academyPlan.private.benefit1': 'تطوير فردي عالي الكثافة',
      'membership.academyPlan.private.benefit2': 'متوافق مع خطة التطوير الفردية للاعب',
      'membership.academyPlan.private.benefit3': 'تمارين خاصة بمركز اللعب',
      'membership.academyPlan.private.benefit4': 'تحليل الفيديو (إضافة اختيارية)',
      'membership.academyPlan.family.tag': 'باقة عائلية',
      'membership.academyPlan.family.title': 'بالغان + طفلان',
      'membership.academyPlan.family.description': 'باقة مجمّعة مصممة للعائلات التي تتدرب معًا في فيجن7.',
      'membership.academyPlan.family.benefit1': 'عضوية صالة رياضية لبالغين',
      'membership.academyPlan.family.benefit2': 'عضوية أكاديمية لطفلين',
      'membership.academyPlan.family.benefit3': 'حجز بادل واحد شهريًا',
      'membership.academyPlan.family.benefit4': 'حفلة عيد ميلاد مجانية',
      'membership.academyPlan.family.benefit5': 'جلستا تدريب شخصي',
      'membership.academyPlan.family.benefit6': 'جلستا تدريب فني خاص',
      'membership.academyPlan.miniKickers.title': 'ميني كيكرز - 3 أشهر',
      'membership.academyPlan.miniKickers.description': 'جلستان أسبوعيًا لمدة 3 أشهر',
      'enquiry.personalInformation': 'المعلومات الشخصية',
      'enquiry.playerDetails': 'بيانات اللاعب',
      'enquiry.orDateOfBirth': 'أو تاريخ الميلاد',
      'profile.fullName': 'الاسم الكامل',
      'profile.email': 'البريد الإلكتروني',
      'profile.phone': 'الهاتف',
      'profile.city': 'المدينة',
      'common.soon': 'قريباً',
    },
  };

  AppLanguage get lang => _lang;
  bool get isReady => _isReady;
  bool get isArabic => _lang == AppLanguage.ar;
  bool get isRTL => _lang == AppLanguage.ar;

  Map<String, String> get _currentMap =>
      _translations[_lang == AppLanguage.ar ? 'ar' : 'en'] ?? _translations['en']!;

  void _loadLanguage() {
    final saved = _prefs.getString(_key);
    if (saved == 'ar') {
      _lang = AppLanguage.ar;
    } else {
      _lang = AppLanguage.en;
    }
    _isReady = true;
    notifyListeners();
  }

  Future<void> setLanguage(AppLanguage lang) async {
    _lang = lang;
    await _prefs.setString(_key, lang == AppLanguage.ar ? 'ar' : 'en');
    notifyListeners();
  }

  String t(String key, {String? fallback}) {
    return _currentMap[key] ?? fallback ?? key;
  }
}

extension TranslationKey on AppLanguage {
  String get key => switch (this) {
    AppLanguage.en => 'en',
    AppLanguage.ar => 'ar',
  };
}
